export const COUNTRY_TIMEZONES: Record<string, string> = {
  'Italia': 'Europe/Rome',
  'Albania': 'Europe/Tirane',
  'Argentina': 'America/Argentina/Buenos_Aires',
  'Australia': 'Australia/Sydney',
  'Austria': 'Europe/Vienna',
  'Belgio': 'Europe/Brussels',
  'Bosnia ed Erzegovina': 'Europe/Sarajevo',
  'Brasile': 'America/Sao_Paulo',
  'Bulgaria': 'Europe/Sofia',
  'Canada': 'America/Toronto',
  'Cile': 'America/Santiago',
  'Cina': 'Asia/Shanghai',
  'Colombia': 'America/Bogota',
  'Croazia': 'Europe/Zagreb',
  'Danimarca': 'Europe/Copenhagen',
  'Ecuador': 'America/Guayaquil',
  'Egitto': 'Africa/Cairo',
  'Estonia': 'Europe/Tallinn',
  'Filippine': 'Asia/Manila',
  'Finlandia': 'Europe/Helsinki',
  'Francia': 'Europe/Paris',
  'Germania': 'Europe/Berlin',
  'Giappone': 'Asia/Tokyo',
  'Grecia': 'Europe/Athens',
  'India': 'Asia/Kolkata',
  'Irlanda': 'Europe/Dublin',
  'Kosovo': 'Europe/Belgrade',
  'Lettonia': 'Europe/Riga',
  'Lituania': 'Europe/Vilnius',
  'Lussemburgo': 'Europe/Luxembourg',
  'Macedonia del Nord': 'Europe/Skopje',
  'Malta': 'Europe/Malta',
  'Marocco': 'Africa/Casablanca',
  'Messico': 'America/Mexico_City',
  'Moldova': 'Europe/Chisinau',
  'Montenegro': 'Europe/Podgorica',
  'Nigeria': 'Africa/Lagos',
  'Norvegia': 'Europe/Oslo',
  'Paesi Bassi': 'Europe/Amsterdam',
  'Pakistan': 'Asia/Karachi',
  'Perù': 'America/Lima',
  'Polonia': 'Europe/Warsaw',
  'Portogallo': 'Europe/Lisbon',
  'Regno Unito': 'Europe/London',
  'Repubblica Ceca': 'Europe/Prague',
  'Romania': 'Europe/Bucharest',
  'Russia': 'Europe/Moscow',
  'Senegal': 'Africa/Dakar',
  'Serbia': 'Europe/Belgrade',
  'Slovacchia': 'Europe/Bratislava',
  'Slovenia': 'Europe/Ljubljana',
  'Spagna': 'Europe/Madrid',
  'Sri Lanka': 'Asia/Colombo',
  'Stati Uniti': 'America/New_York',
  'Svezia': 'Europe/Stockholm',
  'Svizzera': 'Europe/Zurich',
  'Tunisia': 'Africa/Tunis',
  'Turchia': 'Europe/Istanbul',
  'Ucraina': 'Europe/Kyiv',
  'Ungheria': 'Europe/Budapest',
  'Venezuela': 'America/Caracas',
}
